### PR TITLE
JSfuck sleep sort

### PR DESCRIPTION
**Pull request by wademauger**
JSfuck is a language much like JavaScript, but with only four characters. This allows us to reap all the same benefits the nodeJS implementation gives us, without the risk of using the return key or the space bar. Once we rid ourselves of the need for the space bar, Apple will finally be able to release the thinnest MacBook ever, by revolutionizing the space bar, removing it entirely. I think this follows suit with the cutting edge of security as well, depending on not a single dns resolution to run.
# HacktoberfestPRs

### CODE REVIEW

**Comment by mooman219** [comment]
> without the risk of using the return key or the space bar

pls

**Comment by mooman219** [comment]
We have new guidelines for contributing in order to maintain the highest quality of code here at BadSortsTheRepo. Please review the [README.md](https://github.com/mooman219/BadSortsTheRepo/blob/master/README.md).

Please ensure that:
- Input is taking on stdin
- Output is produced on stdout
- A README.md is provided in the source directory outlining the details listed in the [README.md](https://github.com/mooman219/BadSortsTheRepo/blob/master/README.md).

**Comment by wademauger** [comment]
The quality of this project is my highest priority, and I will ammend these requests of pulling shortly, and bigly.

**Comment by wademauger** [comment]
@mooman219 Updated!

**Comment by mooman219** [comment]
@wadeanthony0100 Almost there! Case-sensitivity is a sensitive issue here, could you please update your directories to lowercase. `git mv -f src dest` is the command to rename files. If you're having issues on your OS, try renaming to a temporary destination first. 

`SleepSort/JSfuck/ -> sleepsort/jsfuck/`

**Comment by wademauger** [comment]
This is too much work, I'm boycotting this code base.

**Pull request closed without merging**
