### PR TITLE
Cocktail Shaker Sort in Swift!

### PR DESCRIPTION
**Pull request by DanSwtmn**
It's like bubble sort but worse and neat! But like in Swift!

### CODE REVIEW

**Comment by DanSwtmn** [comment]
Gotta get rid of gnome sort on this branch

**Comment by mooman219** [comment]
Stdin input or bust

**Comment by kristenmills** [comment]
@DanSwtmn I think you mean "marginally better" lol.

**Comment by mooman219** [comment]
@kristenmills It probably gets better cache locality, but memory is cheap and computers are fast so O(n^2) is the new O(1) anyway.

**Pull request merged**
