### PR TITLE
SleepSort with JavaScript

### PR DESCRIPTION
**Pull request by wademauger**
JavaScript's single threaded environment keeps this algorithm's obscene and gluttonous use of system processes in check, leaving other threads open for things like rendering gifs and sending memes to comrades. I think this project deserves a conservative like this to fight for those who still believe in good old family values and enjoy %50 off sushi. 
# HacktoberfestPRs

### CODE REVIEW

**Comment by mooman219** [comment]
We have new guidelines for contributing in order to maintain the highest quality of code here at BadSortsTheRepo. Please review the [README.md](https://github.com/mooman219/BadSortsTheRepo/blob/master/README.md).

Please ensure that:
- Input is taking on stdin
- Output is produced on stdout
- A README.md is provided in the source directory outlining the details listed in the [README.md](https://github.com/mooman219/BadSortsTheRepo/blob/master/README.md).

**Comment by wademauger** [comment]
@mooman219 Updated!

**Comment by DanudeSandstorm** [comment]
@mooman219 when you're merging these in. Make sure to do this one before  #10 since they share code.

For future reference, @wadeanthony0100 you should use different branches if you're creating multiple pull requests (so that same code isn't included in multiple PRs).

**Comment by mooman219** [comment]
@wadeanthony0100 Almost there! Case-sensitivity is a sensitive issue here, could you please update your directories to lowercase. `git mv -f src dest` is the command to rename files. If you're having issues on your OS, try renaming to a temporary destination first. 

`SleepSort/nodeJS/ -> sleepsort/nodejs/`

**Pull request closed without merging**
